name: Suggestion (הצעה)
description: Suggest anything (להציע משהו)
labels: "suggestion"
assignees:
  - TheRealKaup
body:
  - type: markdown
    attributes:
      value: |
        Thanks you for making contact! Please fill the following information (תודה רבה שהחלטת ליצור קשר! בבקשה מלאו את הפרטים הבאים):
  - type: input
    attributes:
      label: Contact information; will appear public (פרטי קשר; יוצג בפומבי)
      description: How can I contact you if more information is needed (איך אוכל ליצור איתך קשר במידה ויש צורך בפרטים נוספים)?
      placeholder: email, discord (דוא"ל, דיסקורד)...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Relevant documents (מסמכים רלוונטיים)
      description: Describe which documents are relevant to your suggestion (לתאר אילו מסמכים רלוונטיים להצעה שלך)
      placeholder: A document, the entire repository (מסמך אחד, כל המאגר)...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Suggestion description (תיאור ההצעה)
      placeholder: Add, change, rephrase (להוסיף, לשנות, לנסח מחדש)...
    validations:
      required: true